apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: srv
data:
  admin-password: YWRtaW4xMjMK
  app-key: NjFhMTBiNjVjMWY5Mjg5MTYxMzhhYzMzOTMxZGI2NTcK
---
apiVersion: v1
kind: Secret
metadata:
  name: wechat
  namespace: srv
data:
  miniprogram-app-id: TFRBSWRzS1RrbXpySVY1Uw==
  miniprogram-secret: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---
apiVersion: v1
kind: Secret
metadata:
  name: aliyun
  namespace: srv
data:
  access-key-id: TFRBSWRzS1RrbXpySVY1Uw==
  access-key-secret: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---
apiVersion: v1
kind: Secret
metadata:
  name: cloopen
  namespace: srv
data:
  account-sid: TFRBSWRzS1RrbXpySVY1Uw==
  app-id: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
  account-token: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---