apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: srv
data:
  admin-password: MTIzNDU2Cg==
  app-key: TFRBSWRzS1RrbXpySVY1Uw==
---
apiVersion: v1
kind: Secret
metadata:
  name: wechat
  namespace: srv
data:
  miniprogram-app-id: TFRBSWRzS1RrbXpySVY1Uw==
  miniprogram-secret: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---
apiVersion: v1
kind: Secret
metadata:
  name: aliyun
  namespace: srv
data:
  access-key-id: TFRBSWRzS1RrbXpySVY1Uw==
  access-key-secret: aHNXRlhYTzdpWnlzcktWSnRvTXp5UmFhRU5RYzJ3
---


