apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
  namespace: gomsa
  labels:
    app: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: api
          image: microhq/micro
          args:
            - "api"
            - "--handler=rpc"
          env:
          - name: PORT
            value: "8080"
          - name: ENV
            value: staging
          - name: MICRO_REGISTRY
            value: "kubernetes"
          ports:
          - containerPort: 8080
