# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greeter-ingress
  namespace: api
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: greeter
            servicePort: greeter-port
---
apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:
    app: greeter
  namespace: api
spec:
  selector:
    app: greeter
  type: ClusterIP
  ports:
    - name: greeter-port
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          command: [
            "/greeter-srv",
            "--selector=static",
            "--server_address=0.0.0.0:8080",
            "--broker_address=0.0.0.0:10001"
          ]
          image: microhq/greeter-srv:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: greeter-port
            protocol: TCP
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=greeter",
            "--server_address=0.0.0.0:8080"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
